exclude: ^test-files/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: pretty-format-json
    args: [--autofix, --no-ensure-ascii]
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: local
  hooks:
  - id: disallow-absolute-paths
    name: disallow absolute paths
    entry: (?i)\b[a-z]:[\/\\][^<>*\"|?]+
    language: pygrep
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 2.2.4
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/asottile/pyupgrade
  rev: v3.16.0
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.4
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.10
  hooks:
  - id: bandit
    args: [-c, pyproject.toml]
    additional_dependencies: ['.[toml]']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:
  - id: mypy
    args: [--install-types, --non-interactive, --show-error-codes]
    additional_dependencies:
    - beautifulsoup4==4.13.4
    - genutility[args,datetime,filesystem,json]==0.0.113
    - lxml==5.4.0
    - pillow==10.4.0
    - platformdirs==4.3.6
    - pycdlib==1.14.0
    - pypdf==4.3.1
    - rich==14.0.0
    - send2trash==1.8.3
    - typing-extensions==4.13.2
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
