name: CI

on: [push]

permissions:
  contents: read

jobs:

  lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: 3.8
    - name: Run linters
      run: |
        python -m pip install ruff
        python -m ruff format . --check
        python -m ruff check .

  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        # windows-2022 yields pdf test errors for no good reason. it works locally...
        # no wheels for rawpy on python 3.8 macos-14
        os: [ubuntu-22.04, macos-14]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
        exclude:
        - os: macos-14
          python-version: '3.8'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: uv sync --all-extras
    - name: Run tests
      run: uv run --all-extras pytest -s -v
